import { useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
	disconnectSocket,
	initiateSocketConnection,
	socket,
	manager,
} from './../library/socketio.service';
export default function Home() {
	useEffect(() => {
		initiateSocketConnection();
		socket.on('connect', () => {
			socket.emit('client-connect', {});
			console.log('connected');
		});
		socket.on('error', (error) => {
			console.log('error', error);
		});

		socket.on('ready-client', (message) => {
			console.log(message);
		});

		socket.on('pong', (message) => {
			console.log(message);
		});

		// let connect with namespace
		// let a = manager.socket('/app');

		// a.on('connect', () => {
		// 	console.log('connected with namespace');
		// });
		// a.on('error', (err) => console.log(err));

		return () => {
			disconnectSocket();
		};
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1>SOcket :)</h1>
			</main>
		</div>
	);
}
